# -*- coding: utf-8 -*-
"""MedyAssignment4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y29DuPAOZiD051Xc4lIWt4b7uq3rO0NN

## Test 8.4; 8.5; 8.6
"""

# Requirements: pandas, numpy, scipy
# pip install pandas numpy scipy

import numpy as np
import pandas as pd
from pathlib import Path
from scipy import stats

# ---------------------- Configuration ----------------------
ALPHA = 0.05  # left-tail probability for ES (e.g., 0.05 = 95% ES)

# ---------------------- ES Helpers ----------------------
def es_left_normal(mu: float, sigma: float, alpha: float = ALPHA) -> float:
    """
    Closed-form left-tail Expected Shortfall for Normal(mu, sigma).
    ES = E[X | X <= q_alpha] where q_alpha is the alpha-quantile.
    ES = mu - sigma * phi(z_alpha) / alpha
    """
    z_alpha = stats.norm.ppf(alpha)
    phi = stats.norm.pdf(z_alpha)
    return mu - sigma * phi / alpha

def es_left_distribution(dist, alpha: float = ALPHA) -> float:
    """
    Generic left-tail ES for a SciPy continuous distribution object (with .ppf and .expect).
    ES = (1/alpha) * ∫_{-∞}^{q_alpha} x f(x) dx
    """
    q_alpha = dist.ppf(alpha)
    # Unconditional truncated moment up to q_alpha, then divide by alpha.
    numerator = dist.expect(lb=-np.inf, ub=q_alpha)
    return numerator / alpha

def es_left_sample(x: np.ndarray, alpha: float = ALPHA) -> float:
    """
    Empirical left-tail ES from a sample x.
    ES_hat = mean of observations <= empirical alpha-quantile.
    """
    x = np.asarray(x)
    q_alpha = np.quantile(x, alpha)
    tail = x[x <= q_alpha]
    # In pathological cases (very small samples), ensure we don't divide by zero
    if tail.size == 0:
        return float(np.min(x))
    return float(np.mean(tail))

# Ensure output directory exists
Path("data").mkdir(parents=True, exist_ok=True)

# ====================== Test 8.4 — ES Normal ======================
# Read data
cin = pd.read_csv("test7_1.csv").to_numpy()
x = cin[:, 0]

# Fit Normal via MLE -> returns (mu_hat, sigma_hat)
mu_hat, sigma_hat = stats.norm.fit(x)

# ES Absolute: ES(Normal(mu_hat, sigma_hat))
es_abs_normal = - es_left_normal(mu_hat, sigma_hat, ALPHA)

# ES Diff from Mean: ES(Normal(0, sigma_hat))
es_diff_from_mean_normal = - es_left_normal(0.0, sigma_hat, ALPHA)

# Write results
out_8_4 = pd.DataFrame({
    "ES Absolute": [es_abs_normal],
    "ES Diff from Mean": [es_diff_from_mean_normal],
})
out_8_4.to_csv("data/testout8_4.csv", index=False)

# ====================== Test 8.5 — ES TDist ======================
cin = pd.read_csv("test7_2.csv").to_numpy()
x = cin[:, 0]

# Fit Student-t via MLE -> returns (df_hat, mu_hat_t, sigma_hat_t)
df_hat, mu_hat_t, sigma_hat_t = stats.t.fit(x)

# ES Absolute: ES(t_{df_hat} with loc=mu_hat_t, scale=sigma_hat_t)
t_abs = stats.t(df_hat, loc=mu_hat_t, scale=sigma_hat_t)
es_abs_t = - es_left_distribution(t_abs, ALPHA)

# ES Diff from Mean: ES(t_{df_hat} with loc=0, scale=sigma_hat_t)
# (Matches Julia: ES(TDist(ν)*σ))
t_diff = stats.t(df_hat, loc=0.0, scale=sigma_hat_t)
es_diff_from_mean_t = - es_left_distribution(t_diff, ALPHA)

out_8_5 = pd.DataFrame({
    "ES Absolute": [es_abs_t],
    "ES Diff from Mean": [es_diff_from_mean_t],
})
out_8_5.to_csv("data/testout8_5.csv", index=False)

# ====================== Test 8.6 — VaR Simulation ======================
# Julia logic:
#   fit_general_t on test7_2, draw 10,000 samples from fitted model,
#   then compute ES(samples) and ES(samples - mean(samples)) empirically.

# Reuse the t fit above (df_hat, mu_hat_t, sigma_hat_t).
# Simulate 10,000 draws from the fitted t distribution.
rng = np.random.default_rng(42)  # set seed for reproducibility
sim = stats.t.rvs(df_hat, loc=mu_hat_t, scale=sigma_hat_t, size=10_000, random_state=rng)

# ES(Absolute) on the simulated returns
es_abs_sim = - es_left_sample(sim, ALPHA)

# ES(Diff from Mean): shift by sample mean, then ES
es_diff_from_mean_sim = - es_left_sample(sim - np.mean(sim), ALPHA)

out_8_6 = pd.DataFrame({
    "ES Absolute": [es_abs_sim],
    "ES Diff from Mean": [es_diff_from_mean_sim],
})
out_8_6.to_csv("data/testout8_6.csv", index=False)


# Check results with given testouts
def compare_csv(file1, file2, tol=1e-2):
    """Compare two CSV files elementwise up to given tolerance."""
    A = pd.read_csv(file1).values
    B = pd.read_csv(file2).values
    if A.shape != B.shape:
        return f"Shape mismatch: {A.shape} vs {B.shape}"
    diff = np.abs(A - B)
    if np.all(diff < tol):
        return "correct"
    else:
        return f"mismatch (max diff={diff.max():.4f})"

pairs = [
    ("data/testout8_4.csv", "testout8_4.csv"),
    ("data/testout8_5.csv", "testout8_5.csv"),
    ("data/testout8_6.csv", "testout8_6.csv"),
]

for f1, f2 in pairs:
    print(f"{f1} vs {f2}: {compare_csv(f1, f2, tol=1e-2)}")

"""## Test 9.1"""

import os
import numpy as np
import pandas as pd
from pathlib import Path
from scipy import stats

# -------------------- Helpers --------------------

def fit_normal(x: np.ndarray):
    mu, sigma = stats.norm.fit(x)
    return {"name": "normal", "mu": mu, "sigma": sigma}

def fit_student_t(x: np.ndarray):
    df, mu, sigma = stats.t.fit(x)   # (df, loc, scale)
    return {"name": "t", "df": df, "mu": mu, "sigma": sigma}

def model_cdf(model, x: np.ndarray):
    if model["name"] == "normal":
        return stats.norm.cdf(x, loc=model["mu"], scale=model["sigma"])
    else:
        return stats.t.cdf(x, df=model["df"], loc=model["mu"], scale=model["sigma"])

def model_ppf(model, u: np.ndarray):
    if model["name"] == "normal":
        return stats.norm.ppf(u, loc=model["mu"], scale=model["sigma"])
    else:
        return stats.t.ppf(u, df=model["df"], loc=model["mu"], scale=model["sigma"])

def gaussian_copula_pca(corr: np.ndarray, n_samples: int, rng=None):
    """Simulate Z ~ N(0, corr) using eigendecomposition (PCA)."""
    corr = np.asarray(corr)
    corr = (corr + corr.T) / 2
    evals, evecs = np.linalg.eigh(corr)
    evals = np.clip(evals, 0.0, None)
    A = evecs @ np.diag(np.sqrt(evals))
    rng = np.random.default_rng() if rng is None else rng
    z = rng.standard_normal(size=(n_samples, corr.shape[0]))
    return z @ A.T

def var_es_from_pnl(pnl: np.ndarray, alpha: float = 0.05):
    """Risk-as-positive convention: VaR = -q_alpha(PnL), ES = -E[PnL | PnL<=q]."""
    q = np.quantile(pnl, alpha)
    var = -q
    tail = pnl[pnl <= q]
    es = -np.mean(tail) if tail.size else -q
    return var, es

# -------------------- Paths & basic setup --------------------
Path("data").mkdir(parents=True, exist_ok=True)
RET_PATH = "data/test9_1_returns.csv"
OUT_PATH = "data/testout9_1.csv"

# -------------------- Read (or create once) returns --------------------
if os.path.exists(RET_PATH):
    # Use the provided returns file (to match expected grader input)
    cin = pd.read_csv(RET_PATH)
else:
    # Only if missing: create a sample file (won't match your expected)
    rng_gen = np.random.default_rng(123)
    A = rng_gen.normal(loc=0.0, scale=0.03, size=200)
    eps = stats.t.rvs(df=10, size=200, random_state=rng_gen) * 0.02
    B = 0.1 * A + eps
    cin = pd.DataFrame({"A": A, "B": B})
    cin.to_csv(RET_PATH, index=False)

# -------------------- 9.1: fit marginals --------------------
models = {
    "A": fit_normal(cin["A"].to_numpy()),
    "B": fit_student_t(cin["B"].to_numpy()),
}

# PIT uniforms, Spearman on U
u_A = model_cdf(models["A"], cin["A"].to_numpy())
u_B = model_cdf(models["B"], cin["B"].to_numpy())
U = np.column_stack([u_A, u_B])

# Spearman via rank->Pearson（稳健且返回 2x2）
R = np.apply_along_axis(stats.rankdata, 0, U)
spcorr = np.corrcoef(R, rowvar=False)
spcorr = (spcorr + spcorr.T) / 2

# -------------------- Copula simulation (fixed seed) --------------------
nSim = 100_000
rng_sim = np.random.default_rng(20240601)  # 固定种子以稳定结果
Z = gaussian_copula_pca(spcorr, nSim, rng=rng_sim)
uSim = stats.norm.cdf(Z)

# Map back to returns
sim_A = model_ppf(models["A"], uSim[:, 0])
sim_B = model_ppf(models["B"], uSim[:, 1])
simRet = pd.DataFrame({"A": sim_A, "B": sim_B})

# -------------------- Portfolio and PnL --------------------
portfolio = pd.DataFrame({
    "Stock": ["A", "B"],
    "currentValue": [2000.0, 3000.0],
})
total_value = portfolio["currentValue"].sum()

# Long-form returns with iteration id
simRet_long = simRet.reset_index(names="iteration").melt(
    id_vars="iteration", var_name="Stock", value_name="ret"
)

# Cross-join (portfolio x iteration) and merge sim returns
iteration_df = pd.DataFrame({"iteration": np.arange(nSim, dtype=int)})
values = portfolio.merge(iteration_df, how="cross").merge(
    simRet_long, on=["iteration", "Stock"], how="left"
)
values["simulatedValue"] = values["currentValue"] * (1.0 + values["ret"])
values["pnl"] = values["simulatedValue"] - values["currentValue"]

# -------------------- Risk per stock --------------------
ALPHA = 0.05
rows = []
for stock, g in values.groupby("Stock", sort=False):
    pnl = g["pnl"].to_numpy()
    var95, es95 = var_es_from_pnl(pnl, alpha=ALPHA)
    cur_val = float(portfolio.loc[portfolio["Stock"] == stock, "currentValue"])
    rows.append({
        "Stock": stock,
        "VaR95": var95,
        "ES95": es95,
        "VaR95_Pct": var95 / cur_val,
        "ES95_Pct": es95 / cur_val,
    })

# -------------------- Total portfolio risk --------------------
pnl_total = values.pivot_table(index="iteration", values="pnl", aggfunc="sum").to_numpy().ravel()
var95_tot, es95_tot = var_es_from_pnl(pnl_total, alpha=ALPHA)
rows.append({
    "Stock": "Total",
    "VaR95": var95_tot,
    "ES95": es95_tot,
    "VaR95_Pct": var95_tot / total_value,
    "ES95_Pct": es95_tot / total_value,
})

risk = pd.DataFrame(rows, columns=["Stock", "VaR95", "ES95", "VaR95_Pct", "ES95_Pct"])
risk.to_csv(OUT_PATH, index=False)
print(f"Wrote {OUT_PATH}")