# -*- coding: utf-8 -*-
"""MedyPanAssignment3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Ac6vIqSrFVBbflTrXk9UP3Nx1l3Zjzo

## Test 5
"""

import numpy as np
import pandas as pd


def symmetrize(A):
    return (A + A.T) / 2.0

def eig_clip_psd(A, eps=0.0):
    """Symmetric eigenvalue clipping."""
    A = symmetrize(A)
    vals, vecs = np.linalg.eigh(A)
    vals_clipped = np.maximum(vals, eps)
    return (vecs * vals_clipped) @ vecs.T

def near_psd_cov(S, eps=0.0):
    """Near-PSD repair for covariance matrices."""
    S2 = eig_clip_psd(S, eps=eps)
    d_old = np.sqrt(np.clip(np.diag(S), 1e-16, None))
    d_new = np.sqrt(np.clip(np.diag(S2), 1e-16, None))
    T = np.diag(d_old / d_new)
    S_new = T @ S2 @ T
    return symmetrize(S_new)

def higham_corr(A, max_iter=100, tol=1e-10):
    """Higham nearest correlation matrix."""
    A = symmetrize(np.array(A, dtype=float))
    Y = A.copy()
    deltaS = np.zeros_like(A)

    for _ in range(max_iter):
        R = Y - deltaS
        R_psd = eig_clip_psd(R, eps=0.0)
        deltaS = R_psd - R
        Y = R_psd.copy()
        np.fill_diagonal(Y, 1.0)

        if np.linalg.norm(Y - R_psd) < tol:
            break

    Y = symmetrize(Y)
    np.fill_diagonal(Y, 1.0)
    return Y

def higham_cov(S, max_iter=100, tol=1e-10):
    """Higham nearest covariance matrix."""
    S = symmetrize(np.array(S, dtype=float))
    std = np.sqrt(np.clip(np.diag(S), 1e-16, None))
    D = np.diag(std)
    Dinv = np.diag(1.0 / std)
    R = Dinv @ S @ Dinv
    Rn = higham_corr(R, max_iter=max_iter, tol=tol)
    Sn = D @ Rn @ D
    return symmetrize(Sn)

# Simulators

def simulate_normal(n, cov, fixMethod=None):
    """Normal simulation with optional PSD fixes."""
    cov = np.array(cov)
    if fixMethod == "near_psd":
        cov = near_psd_cov(cov)
    elif fixMethod == "higham":
        cov = higham_cov(cov)
    mean = np.zeros(cov.shape[0])
    return np.random.multivariate_normal(mean, cov, size=n)

def simulate_pca(cov, n, pctExp=0.99):
    """PCA-based simulation keeping enough PCs to explain pctExp variance."""
    eigvals, eigvecs = np.linalg.eigh(cov)
    idx = np.argsort(eigvals)[::-1]
    eigvals, eigvecs = eigvals[idx], eigvecs[:, idx]
    cumvar = np.cumsum(eigvals) / np.sum(eigvals)
    k = np.searchsorted(cumvar, pctExp) + 1
    L = eigvecs[:, :k] @ np.diag(np.sqrt(eigvals[:k]))
    Z = np.random.randn(n, k)
    return Z @ L.T

def sample_cov(X):
    """Return sample covariance with variables in columns."""
    return np.cov(X, rowvar=False, bias=False)


np.random.seed(4)

# 5.1 PD Input
cin = pd.read_csv("test5_1.csv").values
cout = sample_cov(simulate_normal(100000, cin))
pd.DataFrame(cout).to_csv("medy_testout5_1.csv", index=False)

# 5.2 PSD Input
cin = pd.read_csv("test5_2.csv").values
cout = sample_cov(simulate_normal(100000, cin))
pd.DataFrame(cout).to_csv("medy_testout5_2.csv", index=False)

# 5.3 nonPSD Input: near_psd fix
cin = pd.read_csv("test5_3.csv").values
cout = sample_cov(simulate_normal(100000, cin, fixMethod="near_psd"))
pd.DataFrame(cout).to_csv("medy_testout5_3.csv", index=False)

# 5.4 nonPSD Input: Higham Fix
cin = pd.read_csv("test5_3.csv").values
cout = sample_cov(simulate_normal(100000, cin, fixMethod="higham"))
pd.DataFrame(cout).to_csv("medy_testout5_4.csv", index=False)

# 5.5 PSD Input: PCA Simulation
cin = pd.read_csv("test5_2.csv").values
cout = sample_cov(simulate_pca(cin, 100000, pctExp=0.99))
pd.DataFrame(cout).to_csv("medy_testout5_5.csv", index=False)

# Check results with given testouts

def compare_csv(file1, file2, tol=1e-2):
    """Compare two CSV files elementwise up to given tolerance."""
    A = pd.read_csv(file1).values
    B = pd.read_csv(file2).values
    if A.shape != B.shape:
        return f"Shape mismatch: {A.shape} vs {B.shape}"
    diff = np.abs(A - B)
    if np.all(diff < tol):
        return "correct"
    else:
        return f"mismatch (max diff={diff.max():.4f})"

pairs = [
    ("testout_5.1.csv", "medy_testout5_1.csv"),
    ("testout_5.2.csv", "medy_testout5_2.csv"),
    ("testout_5.3.csv", "medy_testout5_3.csv"),
    ("testout_5.4.csv", "medy_testout5_4.csv"),
    ("testout_5.5.csv", "medy_testout5_5.csv"),
]

for f1, f2 in pairs:
    print(f"{f1} vs {f2}: {compare_csv(f1, f2, tol=1e-2)}")

"""## Test 8: 8.1 to 8.3"""

import numpy as np
import pandas as pd
from scipy.stats import norm, t

ALPHA = 0.05  # Use 95% VaR

def var95(x: np.ndarray) -> float:
    """VaR at 95% confidence for returns x: positive number for loss."""
    x = np.asarray(x).ravel()
    return -np.quantile(x, ALPHA)


# Test 8.1 VaR Normal

cin = pd.read_csv("test7_1.csv").to_numpy()
x = cin[:, 0].astype(float)

mu = np.mean(x)

# population (MLE) std: ddof=0 to align with MLE used in most fit routines
sigma = np.std(x, ddof=0)

# "VaR Absolute": shift by fitted mean
var_abs_norm = -norm.ppf(ALPHA, loc=mu, scale=sigma)

# "VaR Diff from Mean": zero-mean version
var_diff_norm = -norm.ppf(ALPHA, loc=0.0, scale=sigma)

pd.DataFrame({
    "VaR Absolute": [var_abs_norm],
    "VaR Diff from Mean": [var_diff_norm],
}).to_csv("medy_testout8_1.csv", index=False)


# Test 8.2 VaR TDist

cin = pd.read_csv("test7_2.csv").to_numpy()
x = cin[:, 0].astype(float)


# Fit Student-t: returns df, loc (mean-ish), scale (sigma-ish)

# Using MLE; this matches with the fit_general_t
df_hat, loc_hat, scale_hat = t.fit(x)

# "VaR Absolute": with fitted loc & scale
var_abs_t = -t.ppf(ALPHA, df_hat, loc=loc_hat, scale=scale_hat)

# "VaR Diff from Mean": zero-mean but same df & scale
var_diff_t = -t.ppf(ALPHA, df_hat, loc=0.0, scale=scale_hat)

pd.DataFrame({
    "VaR Absolute": [var_abs_t],
    "VaR Diff from Mean": [var_diff_t],
}).to_csv("medy_testout8_2.csv", index=False)



# Test 8.3 VaR Simulation (from fitted t)

# Reuse the t fit on test7_2; simulate 10,000 samples from fitted model
rng = np.random.default_rng()
sim = rng.standard_t(df_hat, size=10_000) * scale_hat + loc_hat

var_abs_sim = var95(sim)
var_diff_sim = var95(sim - np.mean(sim))

pd.DataFrame({
    "VaR Absolute": [var_abs_sim],
    "VaR Diff from Mean": [var_diff_sim],
}).to_csv("medy_testout8_3.csv", index=False)


# Check the testout csv with the given testouts

def compare_csv(file1, file2, tol=1e-2):
    """Compare two CSV files elementwise up to given tolerance."""
    A = pd.read_csv(file1).values
    B = pd.read_csv(file2).values
    if A.shape != B.shape:
        return f"Shape mismatch: {A.shape} vs {B.shape}"
    diff = np.abs(A - B)
    if np.all(diff < tol):
        return "correct"
    else:
        return f"mismatch (max diff={diff.max():.4f})"

pairs = [
    ("testout8_1.csv", "medy_testout8_1.csv"),
    ("testout8_2.csv", "medy_testout8_2.csv"),
    ("testout8_3.csv", "medy_testout8_3.csv"),
]

for f1, f2 in pairs:
    print(f"{f1} vs {f2}: {compare_csv(f1, f2, tol=1e-2)}")