# -*- coding: utf-8 -*-
"""test7.2medypan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EpbYWOneLcsRefdAgm7buCm_i-tMagAa
"""

import numpy as np
import pandas as pd
from scipy.stats import t

# Read the data file
cin2 = pd.read_csv("test7_2.csv")
x2 = pd.to_numeric(cin2.iloc[:, 0], errors="coerce").dropna().to_numpy()

# Fit the student t distribution and return mu, sigma and nu
nu_hat, mu_hat_t, sigma_hat_t = t.fit(x2)

out2 = pd.DataFrame({"mu": [mu_hat_t], "sigma": [sigma_hat_t], "nu": [nu_hat]})
out2.to_csv("testout7_2medypan.csv", index=False, float_format="%.15f")


df = pd.read_csv("testout7_2medypan.csv")
print(df)
assert list(df.columns) == ["mu", "sigma", "nu"]
assert len(df) == 1

def check_output(generated_file, reference_file):

    df1 = pd.read_csv(generated_file)
    df2 = pd.read_csv(reference_file)

    if list(df1.columns) != list(df2.columns) or df1.shape != df2.shape:
        return "not correct"
    A = df1.to_numpy(dtype=float)
    B = df2[df1.columns].to_numpy(dtype=float)

    return "correct" if np.allclose(A, B) else "not correct"

result = check_output("testout7_2.csv", "testout7_2medypan.csv")
print(result)