# -*- coding: utf-8 -*-
"""test7.1medypan

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u4Yk-z-OA71ogFvxVsrNFH0vFJNbNI4X
"""

import numpy as np
import pandas as pd
from scipy.stats import norm, t

# Read the data
cin = pd.read_csv("test7_1.csv")
x = pd.to_numeric(cin.iloc[:, 0], errors="coerce").dropna().to_numpy()

# Fit the normal distribution
mu_hat = float(np.mean(x))
sigma_hat = float(np.std(x, ddof=1))

out1 = pd.DataFrame({"mu": [mu_hat], "sigma": [sigma_hat]})
out1.to_csv("testout7_1medypan.csv", index=False)

df = pd.read_csv("testout7_1medypan.csv")
print(df)
assert list(df.columns) == ["mu", "sigma"]
assert len(df) == 1

def check_output(generated_file, reference_file):

    df1 = pd.read_csv(generated_file)
    df2 = pd.read_csv(reference_file)

    # Compare the results
    if df1.equals(df2):
        return "correct output"
    else:
        return "not correct"

result = check_output("testout7_1.csv", "testout7_1medypan.csv")
print(result)